### PR TITLE
Fix support for Python 3.9

### PR DESCRIPTION
**Pull request by AA-Turner**
Superseeds #156.

A

### CODE REVIEW

**Comment by KyeRussell** [comment]
If I'm not mistaken, this hasn't yet been released to PyPI, yes? If so, could we please get a new release? Thanks very much in advance.

**Comment by Puncher1** [comment]
> If I'm not mistaken, this hasn't yet been released to PyPI, yes? If so, could we please get a new release? Thanks very much in advance.

You can install this commit with pip to get the fix (as I just did, since I had the same error):
```cmd
pip install git+https://github.com/sphinx-doc/sphinx-autobuild.git@55917c69cd6836da81c10b323dc17daf496a4bca
```

**Comment by Borda** [comment]
@Puncher1 thank you, is there an ETA on the release of having it as RC for testing?

**Comment by AA-Turner** [comment]
https://pypi.org/project/sphinx-autobuild/2024.9.3/

A

**Pull request merged**
